module.exports = {
  // mode: 'jit',
  // purge:[
  //     './test-theme-from-theme-builder/modules/**/*.html',
  //   './test-theme-from-theme-builder/modules/**/*.js',
  // ],
  theme: {
    extend: {},
      colors:{
        primary: '#034A7F',
        secondary: '#0086C7',
        gray: {
          DEFAULT : '#DEE1E8',
          light : '#F6F7F9',
          dark : '#6C7893',
          cool : '#3c3c3c',
          medium : '#CACAC9',
        },
        white: '#FFFFFF',
        black: '#000000',
        transparent: 'transparent'
      }
    },
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    animation: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropFilter: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundAttachment: false,
    backgroundBlendMode: false,
    backgroundClip: false,
    backgroundOrigin: false,
    blur: false,
    borderCollapse: false,
    boxDecorationBreak: false,
    caretColor: false,
    filter: false,
    divideColor: false,
    divideStyle: false,
    divideWidth: false,
    gradientColorStops: false,
    grayscale: false,
    divideOpacity: false,
    float: false,
    lineHeight:false,
    accessibility:false,
    alignContent:false,
    alignSelf:false,
    backgroundAttachment:false,
    backgroundClip:false,
    backgroundImage:false,
    backgroundOpacity:false,
    borderOpacity:false,
    clear:false,
    divideColor:false,
    divideOpacity:false,
    divideStyle:false,
    divideWidth:false,
    fontFamily:false,
    fontVariantNumeric:false,
    ringColor:false,
    ringOffsetColor:false,
    ringOffsetWidth:false,
    ringOpacity:false,
    ringWidth:false,
  }
}
