module.exports = {
  purge: [],
  darkMode : false,
  theme: {
    container: {
      padding: '20px',
      center : true
    },
    extend: {},
      colors:{
        'blue' : '#003A79',
        'cyan' : '#3CD2FF',
        'silver' : '#E6E1DC',
        'peach' : '#FFA064',
        'navy' : '#0F192D',
        'silver-light': '#F8F7F6',
        'white' : '#FFFFFF',
        'black' : '#000000',
        'transparent' : 'transparent'
      }
    },
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    animation: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropFilter: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundAttachment: false,
    backgroundBlendMode: false,
    backgroundClip: false,
    backgroundOrigin: false,
    blur: false,
    borderCollapse: false,
    boxDecorationBreak: false,
    caretColor: false,
    filter: false,
    divideColor: false,
    divideStyle: false,
    divideWidth: false,
    gradientColorStops: false,
    grayscale: false,
    divideOpacity: false,
    float: false,
    lineHeight:false,
    accessibility:false,
    alignContent:false,
    alignSelf:false,
    backgroundAttachment:false,
    backgroundClip:false,
    backgroundImage:false,
    backgroundOpacity:false,
    borderOpacity:false,
    clear:false,
    divideColor:false,
    divideOpacity:false,
    divideStyle:false,
    divideWidth:false,
    fontFamily:false,
    fontVariantNumeric:false,
    ringColor:false,
    ringOffsetColor:false,
    ringOffsetWidth:false,
    ringOpacity:false,
    ringWidth:false,
  }
}
